-- CougarConnect Supabase schema
--
-- Recreates the tables SupabaseService.cs and the Models/*.cs classes expect.
-- Run this in the Supabase SQL Editor for the target project (cougarconnect-demo)
-- before pointing the app at it.
--
-- Column/table names are double-quoted to preserve the exact PascalCase the app
-- queries by over PostgREST (e.g. `/rest/v1/Alumni?GradYear=...`) — Postgres would
-- otherwise fold unquoted identifiers to lowercase and every request would 404.

create table if not exists "Alumni" (
    "id" bigint generated by default as identity primary key,
    "First" text not null,
    "Last" text not null,
    "GradYear" text not null,
    "City" text not null,
    "Major" text not null,
    "Company" text,
    "ConnectionList" bigint[],
    "Email" text not null
);

create table if not exists "Messages" (
    "id" bigint generated by default as identity primary key,
    "SenderId" bigint not null,
    "RecipientId" bigint not null,
    "Body" text not null,
    "SentAt" timestamptz not null default now(),
    "IsRead" boolean not null default false
);

create table if not exists "ConnectionRequests" (
    "id" bigint generated by default as identity primary key,
    "RequesterId" bigint not null,
    "RecipientId" bigint not null,
    "RequestSubject" text not null,
    "Message" text not null,
    "Token" text not null unique,
    "Status" text not null default 'Pending',
    "CreatedAt" timestamptz not null default now()
);

create table if not exists "Notifications" (
    "id" bigint generated by default as identity primary key,
    "UserId" bigint not null,
    "Message" text not null,
    "CreatedAt" timestamptz not null default now()
);

create index if not exists idx_messages_recipient_isread on "Messages" ("RecipientId", "IsRead");
create index if not exists idx_messages_sender_recipient on "Messages" ("SenderId", "RecipientId");
create index if not exists idx_connectionrequests_recipient_status on "ConnectionRequests" ("RecipientId", "Status");
create index if not exists idx_connectionrequests_requester_recipient on "ConnectionRequests" ("RequesterId", "RecipientId");
create index if not exists idx_notifications_userid on "Notifications" ("UserId");

-- RLS is intentionally left disabled: the anon key is only ever used server-side by
-- the Blazor Server backend (never sent to the browser), and per-row auth is already
-- handled by ASP.NET Core Identity in front of it. A "RLS disabled" warning in the
-- Supabase Advisor for these four tables is expected and not a real exposure here.
